/**************************************************************************/
/*!
    @file     SolarPowerCalcMethods.hh
    @author1  Justin Albert (jalbert@uvic.ca)
    @author2  Patrick Ryan  (patrick.ryan5787@gmail.com)
    @author3  Aravind Shaj  (aravindshaj@gmail.com)
    @author4  Hannah Swan   (hannah.swan.3.14@gmail.com)
    @license  GPL

    This is the class containing the solar power calculation methods to 
    determine the amount of solar power (in Watts) both generated by the 
    solar panels and collected by the onboard batteries (i.e., accounting 
    for, and thus subtracting, all known losses) at any given time. 

    @section  HISTORY

    v1.0  - First version
*/
/**************************************************************************/

#ifndef __SOLARPOWERCALCMETHODS_HH__
#define __SOLARPOWERCALCMETHODS_HH__

#include <vector>

//              ---------------------
//              -- Class Interface --
//              ---------------------

class SolarPowerCalcMethods {

    public:

        // Get the instantaneous solar power (in Watts) being collected at the present time. 
        static float              getInstantaneousSolarPower();	                   
	
        // Get the integrated solar energy (in Joules) collected over the next minute.
        static float              getSolarEnergyForNextMinute();	                   

// Helper functions, used internally by the above static methods
    protected:

        // Return a 2-element vector containing (in element [0]) the zenith angle (i.e. the angle
        // away from the zenith, in degrees), and (in element [1]) the azimuth angle (i.e. degrees
        // East of true North), of the centre of the solar disc, as viewed from the balloon.
        static std::vector<float> getZenithAndAzAnglesOfSunFromBalloon();  

        // Given the two solar angles as an argument (obtained via getZenithAndAzAnglesOfSunFromBalloon() 
        // above), return the area of the front faces of the solar panels, when projected onto the plane
        // perpendicular to the present vector from the centre of the solar disc to the balloon. 
        static float              getSolarPanelProjectedArea( std::vector<float> solarAngles );            

    private:

        SolarPowerCalcMethods() {} 			// constructor should never be used
};

#endif // __SOLARPOWERCALCMETHODS_HH__
