/**************************************************************************/
/*!
    @file     SolarPowerCalcMethods.hh
    @author1  Justin Albert (jalbert@uvic.ca)
    @author2  Patrick Ryan  (patrick.ryan5787@gmail.com)
    @author3  Aravind Shaj  (aravindshaj@gmail.com)
    @author4  Hannah Swan   (hannah.swan.3.14@gmail.com)
    @license  GPL

    This is the class containing the solar power calculation methods to 
    determine the amount of solar power (in Watts) both generated by the 
    solar panels and collected by the onboard batteries (i.e., accounting 
    for, and thus subtracting, all known losses) at any given time. 

    @section  HISTORY

    v1.0  - First version
*/
/**************************************************************************/

#ifndef __SOLARPOWERCALCMETHODS_HH__
#define __SOLARPOWERCALCMETHODS_HH__

#include <vector>

//              ---------------------
//              -- Class Interface --
//              ---------------------

class SolarPowerCalcMethods {

    public:

        static float getInstantaneousSolarPower();	// get the instantaneous solar power (in Watts) collected at the present time 
	
        static float getSolarEnergyForNextMinute();	// get the integrated solar energy (in Joules) collected over the next minute

        // helper functions, used internally by the above static methods
    protected:

        static float getSolarPanelProjectedArea();      // the area of the front faces of the solar panels, projected onto the plane
                                                        // perpendicular to the present vector from the sun to the balloon 

        static std::vector<float> getSunToBalloonVector();

    private:

        SolarPowerCalcMethods() {} 			// constructor should never be used
};

#endif // __SOLARPOWERCALCMETHODS_HH__
